// Generated by CoffeeScript 2.5.0
(function() {
  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define([], factory);
    } else if (typeof module === 'object') {
      return module.exports = factory();
    } else {
      return root.commify = factory();
    }
  })(this, function() {
    return function(something) {
      var decimals, m, num, ref, whole;
      num = eval(something.toString().trim()).toString();
      if (m = num.match(/([+\-])?(\d+)(\.(\d+))?/)) {
        whole = m[2].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        decimals = ((ref = m[4]) != null ? ref.replace(/(\d{3})(?=\d)/g, function(a, b) {
          return `${b},`;
        }) : void 0) || '';
        if (decimals) {
          decimals = `.${decimals}`;
        }
        return [m[1] || '', whole, decimals].join('');
      } else {
        return num;
      }
    };
  });

}).call(this);
