// Generated by CoffeeScript 2.5.0
// 
//   # adapated from https://stackoverflow.com/a/2901298/2926055
//   try
//     num = something.toString().trim()
//   catch e
//     return ''
//   m = num.match /^([+\-])?(\d+)(\.(\d+))?$/
//   return num if not m
//   whole = m[2].replace /\B(?=(\d{3})+(?!\d))/g, ","
//   decimals = m[4]?.replace(/(\d{3})(?=\d)/g, (a,b) -> "#{b},") or ''
//   decimals = ".#{decimals}" if decimals
//   return [m[1] or '', whole, decimals].join('')

(function() {
  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define([], factory);
    } else if (typeof module === 'object') {
      return module.exports = factory();
    } else {
      return root.commify = factory();
    }
  })(this, function() {
    return function(something) {
      var decimals, e, m, num, ref, whole;

      try {
        num = something.toString().trim();
      } catch (error) {
        e = error;
        return '';
      }

      m = num.match(/^([+\-])?(\d+)(\.(\d+))?$/);

      if (!m) {
        return num;
      }

      whole = m[2].replace(/\B(?=(\d{3})+(?!\d))/g, ",");

      decimals = ((ref = m[4]) != null ? ref.replace(/(\d{3})(?=\d)/g, function(a, b) {
        return `${b},`;
      }) : void 0) || '';

      if (decimals) {
        decimals = `.${decimals}`;
      }

      return [m[1] || '', whole, decimals].join('');
    };
  });

}).call(this);
